version: '3'

services:
   mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:         
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db

   reservations:
    build: 
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: developemnt
    depends_on:
      - mongodb
    env_file:
      - .env
    command: ["yarn", "start:dev", "reservations"]
    ports:
      - '3000:3000'
    volumes:
      - .:/app


volumes:
 mongodb-data:
  driver: local