version: '3'

services:
   mongodb:
    container_name: sleepr_mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:         
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db

   reservations:
    container_name: reservations_app
    build: 
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: developemnt
    depends_on:
      - mongodb
    env_file:
      - ./apps/reservations/.env
    command: ["yarn", "start:dev", "reservations"]
    ports:
      - '3000:3000'
    volumes:
      - .:/app

   auth:
    container_name: auth_app
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: developemnt
    depends_on:
      - mongodb
    env_file:
      - ./apps/auth/.env
    command: ["yarn", "start:dev", "auth"]
    ports:
      - '3001:3001'
    volumes:
      - .:/app


volumes:
 mongodb-data:
  driver: local